#!/bin/bash
#
# Part of Simple paas
#
# Kept as separate script in case there is a need to run manually.
#

docker run \
  --detach \
  --name nginx-proxy \
  --publish 80:80 \
  --publish 443:443 \
  --volume /etc/nginx/certs \
  --volume /etc/nginx/vhost.d \
  --volume /usr/share/nginx/html \
  --volume /var/run/docker.sock:/tmp/docker.sock:ro \
  --volume /etc/simple-paas/proxy.conf:/etc/nginx/conf.d/proxy.conf \
  --restart always \
  jwilder/nginx-proxy:latest

docker run --detach \
  --name nginx-proxy-letsencrypt \
  --volumes-from nginx-proxy \
  --volume /var/run/docker.sock:/var/run/docker.sock:ro \
  --env "DEFAULT_EMAIL=${EMAIL}" \
  --restart always \
  jrcs/letsencrypt-nginx-proxy-companion
